<#
.SYNOPSIS
    Deterministic bounded Planner plan record; planning only, never dispatches.
.DESCRIPTION
    parallel_ok and route are loop composition: decision policies come from
    P34/P36 libraries; composition and stage ordering belong to this loop.
#>
[CmdletBinding()]
param()

function Invoke-OrchestrationPlannerLoop {
    [CmdletBinding()]
    param($Descriptor,$Options=$null)
    $root=Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
    function Read-PL($o,[string]$n,$d=$null) { if($null -eq $o){return $d};if($o -is [System.Collections.IDictionary]){if($o.Contains($n)){return $o[$n]};return $d};$p=$o.PSObject.Properties[$n];if($p){return $p.Value};return $d }
    function Safe-PL($v,[int]$max=300) { $s=[string]$v;$s=$s -replace '(?i)sk-[A-Za-z0-9_-]+','[redacted]' -replace '(?i)(token|secret|password|key)\s*[=:]\s*[^\s,;]+','$1=[redacted]' -replace '(?i)\b[a-z0-9.-]+\.(com|net|org|local|dev|io|br)\b','[redacted-host]' -replace '[\x00-\x1f]',' ';$s=$s.Trim();if($s.Length -gt $max){$s=$s.Substring(0,$max)};return $s }
    function Clean-PL($v,[int]$depth=0) { if($depth -gt 8){return '[depth-cap]'};if($null -eq $v){return $null};if($v -is [string]){return (Safe-PL $v 240)};if($v -is [bool] -or $v -is [ValueType]){return $v};if($v -is [System.Collections.IDictionary]){$h=[ordered]@{};$count=0;foreach($k in @($v.Keys | Sort-Object)){if($count -ge 40){break};$key=Safe-PL ([string]$k) 80;$h[$key]=Clean-PL $v[$k] ($depth+1);$count++};return $h};if($v -is [System.Collections.IEnumerable]){$a=@();foreach($x in $v){if($a.Count -ge 20){break};$a+=@(Clean-PL $x ($depth+1))};return ,$a};$h=[ordered]@{};$count=0;foreach($p in @($v.PSObject.Properties)){if($count -ge 40){break};$h[(Safe-PL $p.Name 80)]=Clean-PL $p.Value ($depth+1);$count++};return $h }
    function Unavailable-PL($why){return [pscustomobject]@{status='unavailable';reason=$why}}
    try {
        $o=$Options; if($null -eq $o){$o=@{}}
        $d=$Descriptor;$invalidDescriptor=($null -eq $d -or ($d -isnot [System.Collections.IDictionary] -and $d -isnot [pscustomobject]))
        if(-not $invalidDescriptor){foreach($field in @('objective','summary','risk','task_shape','scope','uncertainty')){$v=$null;if($d -is [System.Collections.IDictionary]){if($d.Contains($field)){$v=$d[$field]}}else{$prop=$d.PSObject.Properties[$field];if($prop){$v=$prop.Value}};if($null -ne $v -and ($v -is [array] -or $v -is [System.Collections.IDictionary] -or $v -is [pscustomobject] -or $v -is [ValueType])){$invalidDescriptor=$true;break}}}
        if($invalidDescriptor){$d=@{risk='medium';task_shape='invalid';objective='Invalid descriptor; conservative plan.'}}
        $objective=Safe-PL (Read-PL $d 'objective' (Read-PL $d 'summary' 'Insufficient task detail; clarify scope.')) 500
        if(-not $objective){$objective='Insufficient task detail; clarify scope.'}
        $stamp=[string](Read-PL $o 'timestamp' '');$dt=[DateTimeOffset]::MinValue;$timestampNote='';if(-not [DateTimeOffset]::TryParse($stamp,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$dt)){$stamp=[DateTime]::UtcNow.ToString('o');$timestampNote='Invalid timestamp replaced with internal UTC.'}else{$stamp=$dt.UtcDateTime.ToString("yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'",[Globalization.CultureInfo]::InvariantCulture)}
        $frame=[ordered]@{objective=$objective;information_missing=([string](Read-PL $d 'summary' '') -eq '' -and [string](Read-PL $d 'objective' '') -eq '')}
        $reuse=Unavailable-PL 'evidence-store-not-requested'
        $reuseLib=Join-Path $PSScriptRoot 'OrchestrationEvidenceStore.ps1'
        if((Read-PL $o 'store_dir' '') -and (Test-Path -LiteralPath $reuseLib)){try{. $reuseLib;$rr=Find-ReusableOrchestrationEvidence -StoreDir ([string]$o.store_dir) -Scope @((Read-PL $d 'scope' @())) -CurrentSourceFingerprints (Read-PL $d 'source_fingerprints' @{}) -CurrentBaseRevision ([string](Read-PL $d 'base_revision' '')) -CurrentCriteriaHash ([string](Read-PL $d 'criteria_hash' '')) -CurrentEnv (Read-PL $d 'environment' @{}) -Now $stamp -MaxResults 5;if($rr -isnot [array]){throw 'bad reuse shape'};$reuse=[pscustomobject]@{status='ok';results=@($rr | Select-Object -First 5)}}catch{$reuse=Unavailable-PL 'reuse-query-failed'}}
        $stageOverrides=Read-PL $o 'stage_results' @{}
        if((Read-PL $stageOverrides 'reuse' $null)){ $reuse=Read-PL $stageOverrides 'reuse' $reuse }
        $simple=Unavailable-PL 'simplicity-library-unavailable';$simpLib=Join-Path $PSScriptRoot 'OrchestrationSimplicityPolicy.ps1';if(Test-Path -LiteralPath $simpLib){try{. $simpLib;$simple=Build-OrchestrationWorkerContractFields -Descriptor $d -Policy (Read-PL $o 'simplicity_policy' $null);if($null -eq $simple -or $simple -isnot [pscustomobject]){throw 'bad simplicity shape'}}catch{$simple=Unavailable-PL 'simplicity-stage-failed'}};if((Read-PL $stageOverrides 'simplicity' $null)){$simple=Read-PL $stageOverrides 'simplicity' $simple}
        $risk=[string](Read-PL $d 'risk' 'medium');if($risk -notin @('low','medium','high','critical')){$risk='unknown'}
        $uncertainty=[string](Read-PL $d 'uncertainty' 'medium');if($uncertainty -notin @('low','medium','high')){$uncertainty='medium'}
        $validation=Unavailable-PL 'validation-library-unavailable';$level='L2';$roles=@('coder','tester','reviewer');$completion=Unavailable-PL 'validation-library-unavailable'
        $valLib=Join-Path $PSScriptRoot 'OrchestrationValidationPolicy.ps1';if(Test-Path -LiteralPath $valLib){try{. $valLib;$vp=Read-PL $o 'validation_policy' $null;$vd=Get-OrchestrationValidationLevel -Descriptor $d -Policy $vp;if($null -eq $vd -or [string]$vd.level -notin @('L0','L1','L2','L3') -or $null -eq $vd.required_roles){throw 'bad validation shape'};$level=[string]$vd.level;$roles=@($vd.required_roles | ForEach-Object {Safe-PL $_ 64});$validation=[pscustomobject]@{status=(Safe-PL $vd.status 40);level=$level;required_roles=$roles;rationale=(Safe-PL $vd.rationale 160)};$completion=Test-OrchestrationCompletionPolicy -Level $level -CompletedRoles @() -Descriptor $d -Policy $vp;if($null -eq $completion -or $null -eq $completion.allowed){throw 'bad completion shape'}}catch{$validation=Unavailable-PL 'validation-stage-failed';$completion=Unavailable-PL 'completion-stage-failed';$level='L3';$roles=@('coder','tester','reviewer','security-reviewer')}};if((Read-PL $stageOverrides 'validation' $null)){$validation=Read-PL $stageOverrides 'validation' $validation;$level='L3';$roles=@('coder','tester','reviewer','security-reviewer');$completion=Unavailable-PL 'completion-stage-failed'}
        $mode=Unavailable-PL 'execution-mode-library-unavailable';$modeLib=Join-Path $PSScriptRoot 'OrchestrationExecutionModes.ps1';if(Test-Path -LiteralPath $modeLib){try{. $modeLib;$mode=Get-OrchestrationExecutionMode -Descriptor $d -Policy (Read-PL $o 'execution_mode_policy' $null);if($null -eq $mode -or [string]$mode.mode -notin @('A','B','C') -or [string]::IsNullOrWhiteSpace([string]$mode.rationale)){throw 'bad mode shape'}}catch{$mode=Unavailable-PL 'execution-mode-stage-failed'}};if((Read-PL $stageOverrides 'execution_mode' $null)){$mode=Read-PL $stageOverrides 'execution_mode' $mode}
        foreach($stageName in @('reuse','simplicity','validation','execution_mode','complete_requirements')){$stageValue=Read-PL $stageOverrides $stageName $null;if($null -ne $stageValue -and $stageValue -isnot [pscustomobject] -and $stageValue -isnot [System.Collections.IDictionary]){switch($stageName){'reuse'{$reuse=Unavailable-PL 'malformed-stage-result'};'simplicity'{$simple=Unavailable-PL 'malformed-stage-result'};'validation'{$validation=Unavailable-PL 'malformed-stage-result';$level='L3';$roles=@('coder','tester','reviewer','security-reviewer');$completion=Unavailable-PL 'malformed-stage-result'};'execution_mode'{$mode=Unavailable-PL 'malformed-stage-result'};'complete_requirements'{$completion=Unavailable-PL 'malformed-stage-result'}}}}
        $completionOverride=Read-PL $stageOverrides 'complete_requirements' $null;if($null -ne $completionOverride -and ($completionOverride -is [pscustomobject] -or $completionOverride -is [System.Collections.IDictionary])){$completion=$completionOverride}
        $vOverride=Read-PL $stageOverrides 'validation' $null;if($null -ne $vOverride -and ($vOverride -is [pscustomobject] -or $vOverride -is [System.Collections.IDictionary])){if([string](Read-PL $vOverride 'level' '') -in @('L0','L1','L2','L3') -and $null -ne (Read-PL $vOverride 'required_roles' $null)){$level=[string](Read-PL $vOverride 'level' 'L3');$roles=@((Read-PL $vOverride 'required_roles' @()) | ForEach-Object {Safe-PL $_ 64});$validation=$vOverride}else{$validation=Unavailable-PL 'malformed-stage-result';$level='L3';$roles=@('coder','tester','reviewer','security-reviewer');$completion=Unavailable-PL 'malformed-stage-result'}}
        $budgetAvailable=[bool](Read-PL $d 'validation_budget_available' $true);$budget=[ordered]@{status='record-only';validation_reserved=$budgetAvailable;review_reserved=$budgetAvailable;reserved_before_dispatch=$true;note='Reservation declared only; no execution/budget mutation.'}
        $nontrivial=($level -notin @('L0','L1') -or $risk -in @('medium','high','critical','unknown'))
        $independent=[bool](Read-PL $d 'work_independent' $false);$ownershipClear=[bool](Read-PL $d 'ownership_clear' $false);$shared=[bool](Read-PL $d 'shared_state' $true);$latency=[bool](Read-PL $d 'latency_benefit' $false);$synthesis=[bool](Read-PL $d 'synthesis_affordable' $false)
        $parallel=($independent -and $ownershipClear -and -not $shared -and $latency -and $synthesis -and $budgetAvailable -and $nontrivial)
        $workers=@('coder');if($nontrivial){$workers=@('coder','tester');if($level -in @('L2','L3')){$workers+=@('reviewer')};if($level -eq 'L3'){$workers+=@('security-reviewer')}}
        if(-not $budgetAvailable){$workers=@('coder');$parallel=$false}
        $dispatch=[ordered]@{workers=@($workers | Select-Object -Unique);parallel_ok=[bool]$parallel;parallel_rationale=$(if($parallel){'Independent ownership, bounded validation budget, latency benefit, no shared state, synthesis affordable.'}else{'Sequential/minimum route: parallel prerequisites not all proven.'});separation_rationale=(Safe-PL (Read-PL $d 'separation_rationale' '') 160);escalations=@()}
        if([bool](Read-PL $d 'information_missing' $frame.information_missing)){$dispatch.recommendation='Explorer/Researcher';$dispatch.escalations=@([pscustomobject]@{type='information-gathering';rationale='Resolve missing information before role/tool/model escalation.'})}
        $jev=Unavailable-PL 'jev-trigger-library-unavailable';$jevLib=Join-Path $PSScriptRoot 'OrchestrationJevAdvisory.ps1';if(Test-Path -LiteralPath $jevLib){try{. $jevLib;$jt=Test-JevAdvisoryTrigger -Descriptor $d;if($null -eq $jt -or $null -eq $jt.should_consult -or [string]::IsNullOrWhiteSpace([string]$jt.trigger_reason)){throw 'bad jev shape'};$jev=[pscustomobject]@{should_consult=[bool]$jt.should_consult;reason=(Safe-PL $jt.trigger_reason 80);jev_advisory=$true;authority='non-authoritative-recommendation'}}catch{$jev=Unavailable-PL 'jev-trigger-stage-failed'}};if((Read-PL $stageOverrides 'jev' $null)){$jev=Read-PL $stageOverrides 'jev' $jev};$jevOverride=Read-PL $stageOverrides 'jev' $null;if($null -ne $jevOverride -and $jevOverride -isnot [pscustomobject] -and $jevOverride -isnot [System.Collections.IDictionary]){$jev=Unavailable-PL 'malformed-stage-result'}
        $missing=@($roles)
        if($invalidDescriptor){$level='L2';$roles=@('coder','tester','reviewer');$completion=Unavailable-PL 'invalid-descriptor-conservative';$mode=[pscustomobject]@{mode='C';rationale='Invalid descriptor; conservative fallback.'};$workers=@('coder');$parallel=$false;$validation=[pscustomobject]@{status='unavailable';level='L2';required_roles=$roles};$dispatch.workers=$workers;$dispatch.parallel_ok=$false;$dispatch.escalations=@()}
        $plan=[ordered]@{frame=$frame;reuse=$reuse;simplicity=[pscustomobject]@{status='ok';contract=$simple};risk_uncertainty=[ordered]@{risk=$risk;uncertainty=$uncertainty};execution_mode=$mode;budget_reservation=$budget;dispatch_plan=$dispatch;validation=[pscustomobject]@{status=$validation.status;level=$level;required_roles=$roles};validation_gaps=[ordered]@{missing_roles=$roles;missing_evidence=@()};complete_requirements=$completion;jev_triggers=$jev;jev_advisory=[ordered]@{authoritative=$false;kernel_authority='planner/kernel';recommendation_only=$true};stop_condition=(Safe-PL (Read-PL $d 'stop_condition' 'Stop when sufficient evidence supports the current decision; do not expand scope.') 300);generated_at=(Safe-PL $stamp 80);timestamp_note=$timestampNote}
        $plan=Clean-PL $plan
        $json=ConvertTo-Json -InputObject $plan -Depth 16 -Compress
        if([Text.Encoding]::UTF8.GetByteCount($json) -gt 8192){$plan.reuse=Unavailable-PL 'discarded-plan-size';$plan.simplicity=[pscustomobject]@{status='unavailable';reason='discarded-plan-size'};$plan.jev_triggers=Unavailable-PL 'discarded-plan-size';$plan.validation_gaps.missing_evidence=@();$json=ConvertTo-Json -InputObject $plan -Depth 12 -Compress}
        if([Text.Encoding]::UTF8.GetByteCount($json) -gt 8192){$plan.frame.objective='[truncated]';$plan.dispatch_plan.separation_rationale='';$json=ConvertTo-Json -InputObject $plan -Depth 8 -Compress}
        $oversized=$false
        if([Text.Encoding]::UTF8.GetByteCount($json) -gt 8192){
            $oversized=$true
            # Last resort is a distinct minimal valid record, never a partial JSON string.
            $ref=Safe-PL (Read-PL $d 'task_ref' (Read-PL $d 'task_id' 'unknown')) 120
            $plan=[ordered]@{status='oversized';truncated=$true;oversized=$true;task_ref=([string]$ref.Length+':'+$ref);generated_at=(Safe-PL $stamp 80)}
            $json=ConvertTo-Json -InputObject $plan -Depth 4 -Compress
        }
        return [pscustomobject]@{status=$(if($oversized){'oversized'}else{'ok'});plan=[pscustomobject]$plan;plan_json=$json;byte_length=[Text.Encoding]::UTF8.GetByteCount($json);bounded=([Text.Encoding]::UTF8.GetByteCount($json) -le 8192);truncated=[bool]$oversized;oversized=[bool]$oversized;discard_order=@('reuse results','simplicity details','Jev trigger detail','optional rationale','free text progressive len:value truncation','replace with minimum valid envelope')}
    } catch {return [pscustomobject]@{status='error';plan=$null;reason='planner-loop-failed'}}
}
