<# PowerShell 5.1 compatible local evidence store. No process or network access. #>
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
if($null -eq $script:OrchestrationEvidenceMetricLockSkips){$script:OrchestrationEvidenceMetricLockSkips=0}
if($null -eq $script:OrchestrationEvidenceMetricWriteErrors){$script:OrchestrationEvidenceMetricWriteErrors=0}

function ConvertTo-OrchestrationEvidenceSafeText {
    param([string]$Value, [int]$MaxLength = 240)
    if ($null -eq $Value) { return '' }
    $v = $Value -replace '(?i)sk-[A-Za-z0-9_-]+','[REDACTED]' -replace '(?i)(token|secret|password|key)\s*[=:]\s*[^\s,;]+','$1=[REDACTED]' -replace '(?i)\b[a-z0-9.-]+\.(com|net|org|local|dev|io|br)\b','[REDACTED-HOST]'
    if ($v.Length -gt $MaxLength) { $v = $v.Substring(0,$MaxLength) }
    return $v
}

function Get-OrchestrationEvidenceHash {
    param([string]$Text, [int]$Length = 32)
    $sha = [Security.Cryptography.SHA256]::Create()
    try { $hash = ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','').ToLowerInvariant() } finally { $sha.Dispose() }
    return $hash.Substring(0,[Math]::Min($Length,$hash.Length))
}

function Get-OrchestrationEvidenceValue { param($Object,[string]$Name,$Default=$null)
    if ($null -eq $Object) { return $Default }; $p=$Object.PSObject.Properties[$Name]; if ($null -ne $p) { return $p.Value }; if ($Object -is [System.Collections.IDictionary] -and $Object.Contains($Name)) { return $Object[$Name] }; return $Default
}

function New-OrchestrationEvidenceRecord {
    [CmdletBinding()]
    param([Parameter(Mandatory=$true)]$Evidence,[Parameter(Mandatory=$true)][string]$StoreDir,[int]$MaxRecordBytes=32768,[int]$MaxItems=100,[int]$LockTimeoutMs=100)
    try {
        foreach($k in @('task_id','run_id','worker_id','base_revision','source_fingerprints','scope','command','environment','result','created_at','provenance')) { if($null -eq (Get-OrchestrationEvidenceValue $Evidence $k)){return [pscustomobject]@{created=$false;reason=('missing-'+$k);record=$null}} }
        foreach($k in @('task_id','run_id','worker_id')){$id=[string](Get-OrchestrationEvidenceValue $Evidence $k);if($id.Length -gt 128 -or $id -notmatch '^[A-Za-z0-9._:-]{1,128}$'){return [pscustomobject]@{created=$false;reason=('invalid-'+$k);record=$null}}}
        $sources=[ordered]@{}; $src=Get-OrchestrationEvidenceValue $Evidence 'source_fingerprints';$sourceCount=0
        if($src -is [System.Collections.IDictionary]){foreach($key in $src.Keys){if($sourceCount -ge $MaxItems){break};$sources[(ConvertTo-OrchestrationEvidenceSafeText ([string]$key) 240)]=ConvertTo-OrchestrationEvidenceSafeText ([string]$src[$key]) 128;$sourceCount++}}else{foreach($p in $src.PSObject.Properties){if($sourceCount -ge $MaxItems){break};$sources[(ConvertTo-OrchestrationEvidenceSafeText $p.Name 240)]=ConvertTo-OrchestrationEvidenceSafeText ([string]$p.Value) 128;$sourceCount++}}
        $result=Get-OrchestrationEvidenceValue $Evidence 'result'; $raw=Get-OrchestrationEvidenceValue $result 'raw_content'; $rawRef=Get-OrchestrationEvidenceValue $result 'raw_ref'; $byteLen=0
        if($null -ne $raw){$byteLen=[Text.Encoding]::UTF8.GetByteCount([string]$raw);$rawRef=Get-OrchestrationEvidenceValue $result 'raw_ref'; if([string]::IsNullOrWhiteSpace([string]$rawRef)){return [pscustomobject]@{created=$false;reason='raw-ref-required';record=$null}}}
        $scope=@(Get-OrchestrationEvidenceValue $Evidence 'scope' @() | Select-Object -First $MaxItems | ForEach-Object { ConvertTo-OrchestrationEvidenceSafeText ([string]$_) 240 })
        $assumptions=@(); $assumptionInput=Get-OrchestrationEvidenceValue $Evidence 'assumptions'; if($null -ne $assumptionInput){$assumptions=@($assumptionInput | Select-Object -First $MaxItems | ForEach-Object { ConvertTo-OrchestrationEvidenceSafeText ([string]$_) 240 })}
        $conditions=@(); $conditionBytes=0; $conditionCount=0; $conditionInput=Get-OrchestrationEvidenceValue $Evidence 'invalidation_conditions'; if($null -ne $conditionInput){foreach($inputCondition in $conditionInput){$conditionCount++;if($conditionCount -gt 20){return [pscustomobject]@{created=$false;reason='conditions-too-many';record=$null}};$type=[string](Get-OrchestrationEvidenceValue $inputCondition 'type');$allowed=@{ 'source-changed'=@('type','paths');'criteria-changed'=@('type','hash');'base-revision'=@('type','require_same');'env-changed'=@('type','runtime','version');'ttl'=@('type','expires_at') };if(-not $allowed.ContainsKey($type)){return [pscustomobject]@{created=$false;reason='unknown-invalidation-type';record=$null}};if($inputCondition -is [System.Collections.IDictionary]){$propertyNames=$inputCondition.Keys}else{$propertyNames=$inputCondition.PSObject.Properties|ForEach-Object{$_.Name}};foreach($propertyName in $propertyNames){if($propertyName -notin $allowed[$type]){return [pscustomobject]@{created=$false;reason='unexpected-invalidation-field';record=$null}}};$c=[ordered]@{type=$type};switch($type){'source-changed' {$paths=@();$pathInput=Get-OrchestrationEvidenceValue $inputCondition 'paths' @();$pathCount=0;foreach($path in $pathInput){$pathCount++;if($pathCount -gt 100){return [pscustomobject]@{created=$false;reason='condition-cap';record=$null}};$paths+=@(ConvertTo-OrchestrationEvidenceSafeText ([string]$path) 240)};$c.paths=$paths};'criteria-changed' {$c.hash=ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $inputCondition 'hash')) 128};'base-revision' {$same=Get-OrchestrationEvidenceValue $inputCondition 'require_same' $true;if($same -isnot [bool]){return [pscustomobject]@{created=$false;reason='invalid-base-revision-policy';record=$null}};$c.require_same=$same};'env-changed' {$c.runtime=ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $inputCondition 'runtime')) 80;$c.version=ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $inputCondition 'version')) 80};'ttl' {$exp=[DateTimeOffset]::MinValue;$expText=[string](Get-OrchestrationEvidenceValue $inputCondition 'expires_at');if(-not [DateTimeOffset]::TryParse($expText,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$exp)){return [pscustomobject]@{created=$false;reason='invalid-ttl';record=$null}};$c.expires_at=$exp.UtcDateTime.ToString('o')}};$cJson=ConvertTo-Json -InputObject $c -Depth 8 -Compress;$conditionBytes+=[Text.Encoding]::UTF8.GetByteCount($cJson);if($conditionBytes -gt 16384){return [pscustomobject]@{created=$false;reason='conditions-oversized';record=$null}};$conditions+=@([pscustomobject]$c)}}
        $created=[string](Get-OrchestrationEvidenceValue $Evidence 'created_at'); $parsed=[DateTimeOffset]::MinValue
        if(-not [DateTimeOffset]::TryParse($created,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$parsed)){return [pscustomobject]@{created=$false;reason='invalid-created-at';record=$null}}
        $prov=Get-OrchestrationEvidenceValue $Evidence 'provenance';$role=ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $prov 'created_by')) 64;$kernelRef=ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $prov 'kernel_task_ref')) 128;if(-not $role -or -not $kernelRef){return [pscustomobject]@{created=$false;reason='invalid-provenance';record=$null}}
        $record=[ordered]@{schema_version=1;evidence_id='';task_id=(Get-OrchestrationEvidenceValue $Evidence 'task_id');run_id=(Get-OrchestrationEvidenceValue $Evidence 'run_id');worker_id=(Get-OrchestrationEvidenceValue $Evidence 'worker_id');provenance=[ordered]@{created_by=$role;kernel_task_ref=$kernelRef};base_revision=(ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $Evidence 'base_revision')) 80);criteria_hash=(ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $Evidence 'criteria_hash')) 128);source_fingerprints=$sources;diff_hash=(ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $Evidence 'diff_hash')) 128);scope=$scope;command=(ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $Evidence 'command')) 240);environment=[ordered]@{runtime=(ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue (Get-OrchestrationEvidenceValue $Evidence 'environment') 'runtime')) 80);version=(ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue (Get-OrchestrationEvidenceValue $Evidence 'environment') 'version')) 80)};result=[ordered]@{summary=(ConvertTo-OrchestrationEvidenceSafeText ([string](Get-OrchestrationEvidenceValue $result 'summary')) 240);raw_ref=(ConvertTo-OrchestrationEvidenceSafeText ([string]$rawRef) 240);byte_len=$byteLen};assumptions=$assumptions;invalidation_conditions=$conditions;created_at=$parsed.UtcDateTime.ToString('o');redacted=$true}
        $material=ConvertTo-Json -InputObject $record -Depth 20 -Compress; $record.evidence_id=Get-OrchestrationEvidenceHash $material
        $json=ConvertTo-Json -InputObject $record -Depth 20 -Compress; if([Text.Encoding]::UTF8.GetByteCount($json) -gt $MaxRecordBytes){return [pscustomobject]@{created=$false;reason='record-too-large';record=$null}}
        if(-not (Test-Path -LiteralPath $StoreDir -PathType Container)){[void][IO.Directory]::CreateDirectory($StoreDir)}
        $lock=$null
        $deadline=[DateTime]::UtcNow.AddMilliseconds([Math]::Max(0,$LockTimeoutMs));do{try {$lock=[IO.File]::Open((Join-Path $StoreDir '.evidence.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);break}catch{Start-Sleep -Milliseconds 10}}while([DateTime]::UtcNow -lt $deadline)
        if($null -eq $lock){[void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='lock_busy_skips';reason='lock-busy'});return [pscustomobject]@{created=$false;reason='lock-busy';record=$null}}
        try {$recordPath=Join-Path $StoreDir ($record.evidence_id+'.json');if(Test-Path -LiteralPath $recordPath){$existing=[IO.File]::ReadAllText($recordPath);if($existing -cne $json){[void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='errors';reason='record-conflict'});return [pscustomobject]@{created=$false;reason='record-conflict';record=$null}};return [pscustomobject]@{created=$true;reason='idempotent';record=[pscustomobject]$record}};try{[IO.File]::WriteAllText($recordPath,$json,[Text.Encoding]::UTF8)}catch{[void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='errors';reason='record-write-failed'});return [pscustomobject]@{created=$false;reason='record-write-failed';record=$null}}; [void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='records_created';reason='created'}); return [pscustomobject]@{created=$true;reason='';record=[pscustomobject]$record}} finally {$lock.Dispose()}
    } catch { try{[void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='errors';reason='record-access-failed'})}catch{};return [pscustomobject]@{created=$false;reason='record-access-failed';record=$null} }
}

function Test-OrchestrationEvidenceValidity {
    [CmdletBinding()] param($Record,$Current)
    $reasons=@(); $conditions=@(Get-OrchestrationEvidenceValue $Record 'invalidation_conditions' @())
    foreach($c in $conditions){$type=[string](Get-OrchestrationEvidenceValue $c 'type'); switch($type){
        'source-changed' { $paths=@(Get-OrchestrationEvidenceValue $c 'paths' @()); foreach($path in $paths){$old=Get-OrchestrationEvidenceValue (Get-OrchestrationEvidenceValue $Record 'source_fingerprints') ([string]$path);$new=Get-OrchestrationEvidenceValue (Get-OrchestrationEvidenceValue $Current 'current_source_fingerprints') ([string]$path);if($null -eq $new){$reasons+='source-state-missing'}elseif([string]$old -cne [string]$new){$reasons+=('source-changed:'+ $path)}} }
        'criteria-changed' {if([string](Get-OrchestrationEvidenceValue $Record 'criteria_hash') -cne [string](Get-OrchestrationEvidenceValue $Current 'current_criteria_hash')){$reasons+='criteria-changed'}}
        'base-revision' {if((Get-OrchestrationEvidenceValue $c 'require_same' $true) -and [string](Get-OrchestrationEvidenceValue $Record 'base_revision') -cne [string](Get-OrchestrationEvidenceValue $Current 'current_base_revision')){$reasons+='base-revision'}}
        'env-changed' {$a=Get-OrchestrationEvidenceValue $Record 'environment';$b=Get-OrchestrationEvidenceValue $Current 'current_env';if([string](Get-OrchestrationEvidenceValue $a 'runtime') -cne [string](Get-OrchestrationEvidenceValue $b 'runtime') -or [string](Get-OrchestrationEvidenceValue $a 'version') -cne [string](Get-OrchestrationEvidenceValue $b 'version')){$reasons+='env-changed'}}
        'ttl' {$created=[DateTimeOffset]::MinValue;$now=[DateTimeOffset]::MinValue;$okExp=[DateTimeOffset]::TryParse([string](Get-OrchestrationEvidenceValue $c 'expires_at'),[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$created);$okNow=[DateTimeOffset]::TryParse([string](Get-OrchestrationEvidenceValue $Current 'now'),[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::RoundtripKind,[ref]$now);if(-not $okExp -or -not $okNow -or $now -gt $created){$reasons+='ttl'}}
        default {$reasons+='invalid-invalidation-condition'}
    }}
    return [pscustomobject]@{reusable=($reasons.Count -eq 0);reasons=@($reasons)}
}

function Write-OrchestrationEvidenceMetric { param([string]$StoreDir,$Metric,[int]$MaxBytes=262144)
    try {$path=Join-Path $StoreDir 'reuse-metrics.jsonl';$row=[ordered]@{timestamp=[DateTime]::UtcNow.ToString('o');metric=(ConvertTo-OrchestrationEvidenceSafeText ([string]$Metric.metric) 40);reason=(ConvertTo-OrchestrationEvidenceSafeText ([string]$Metric.reason) 120)};$line=(ConvertTo-Json $row -Compress)+"`n";$size=[Text.Encoding]::UTF8.GetByteCount($line);if($size -gt 512){return $false};$lock=$null;try{$lock=[IO.File]::Open((Join-Path $StoreDir '.metrics.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)}catch{$script:OrchestrationEvidenceMetricLockSkips++;return $false};try {if((Test-Path $path) -and ((Get-Item $path).Length+$size -gt $MaxBytes)){return $false};$s=[IO.File]::Open($path,[IO.FileMode]::Append,[IO.FileAccess]::Write,[IO.FileShare]::None);try {$b=[Text.Encoding]::UTF8.GetBytes($line);$s.Write($b,0,$b.Length);$s.Flush()}finally{$s.Dispose()};return $true}finally{$lock.Dispose()}}catch{$script:OrchestrationEvidenceMetricWriteErrors++;return $false}
}

function Find-ReusableOrchestrationEvidence {
    [CmdletBinding()] param([string]$StoreDir,[string[]]$Scope,[hashtable]$CurrentSourceFingerprints,[string]$CurrentBaseRevision,[string]$CurrentCriteriaHash,$CurrentEnv,[string]$Now=([DateTime]::UtcNow.ToString('o')),[int]$MaxResults=10)
    $found=@();$context=@{current_source_fingerprints=$CurrentSourceFingerprints;current_base_revision=$CurrentBaseRevision;current_criteria_hash=$CurrentCriteriaHash;current_env=$CurrentEnv;now=$Now}
    try {$MaxResults=[Math]::Min(100,[Math]::Max(1,$MaxResults));$files=@(Get-ChildItem -LiteralPath $StoreDir -Filter '*.json' -File | Select-Object -First 1000);foreach($f in $files){try{if($f.Length -gt 32768){throw 'oversized'};$r=ConvertFrom-Json ([IO.File]::ReadAllText($f.FullName));if($r.schema_version -ne 1 -or [string]$r.evidence_id -notmatch '^[a-f0-9]{32}$' -or $r.result -eq $null -or -not $r.task_id -or -not $r.run_id -or -not $r.worker_id -or -not $r.provenance.kernel_task_ref -or @($r.invalidation_conditions).Count -gt 20){throw 'invalid schema'};$valid=Test-OrchestrationEvidenceValidity $r $context;$scopeOk=$true;foreach($s in $Scope){if($r.scope -notcontains $s){$scopeOk=$false}};if($valid.reusable -and $scopeOk){$found+=@([pscustomobject]@{record=$r;created_at=$r.created_at})}else{$reason='scope-mismatch';if(-not $valid.reusable){$reason=$valid.reasons -join ','};[void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='reuse_misses';reason=$reason})}}catch{[void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='records_skipped_invalid';reason='invalid-record'})}}
        $sorted=@($found | Sort-Object { [DateTimeOffset]::Parse($_.created_at) } -Descending | Select-Object -First $MaxResults);$out=@($sorted | ForEach-Object {$r=$_.record;[pscustomobject]@{evidence_id=$r.evidence_id;raw_ref=$r.result.raw_ref;byte_len=$r.result.byte_len;summary=$r.result.summary}});if($out.Count -gt 0){[void](Write-OrchestrationEvidenceMetric $StoreDir @{metric='reuse_hits';reason='reusable'})};return ,$out
    } catch {return ,@()}
}

function Get-OrchestrationEvidenceRaw {
    [CmdletBinding()] param([string]$RawPath,[Parameter(Mandatory=$true)][string]$StoreRoot,[int]$MaxBytes=1048576)
    try {$root=[IO.Path]::GetFullPath($StoreRoot).TrimEnd([IO.Path]::DirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar;$full=[IO.Path]::GetFullPath($RawPath);if(-not $full.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){return [pscustomobject]@{retrieved=$false;reason='raw-path-outside-store';content=$null}};$walk=$full;$insideRoot=$false;for($depth=0;$depth -lt 32 -and $walk;$depth++){$item=Get-Item -LiteralPath $walk -Force -ErrorAction Stop;if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0){return [pscustomobject]@{retrieved=$false;reason='raw-path-reparse';content=$null}};$walk=[IO.Path]::GetDirectoryName($walk.TrimEnd([IO.Path]::DirectorySeparatorChar));if($walk -and ($walk.TrimEnd([IO.Path]::DirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar).StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){$insideRoot=$true};if($walk -and [IO.Path]::GetFullPath($walk).TrimEnd([IO.Path]::DirectorySeparatorChar) -eq $root.TrimEnd([IO.Path]::DirectorySeparatorChar)){$insideRoot=$true;break}};if(-not $insideRoot){return [pscustomobject]@{retrieved=$false;reason='raw-path-outside-store';content=$null}};if($MaxBytes -lt 1){return [pscustomobject]@{retrieved=$false;reason='invalid-cap';content=$null}};$stream=[IO.File]::Open($full,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$buffer=New-Object byte[] ($MaxBytes+1);$total=0;while($total -lt $buffer.Length){$n=$stream.Read($buffer,$total,$buffer.Length-$total);if($n -eq 0){break};$total+=$n};if($total -gt $MaxBytes){return [pscustomobject]@{retrieved=$false;reason='raw-cap-exceeded';content=$null}};$content=[Text.Encoding]::UTF8.GetString($buffer,0,$total);return [pscustomobject]@{retrieved=$true;reason='';content=$content}}finally{$stream.Dispose()}}catch{return [pscustomobject]@{retrieved=$false;reason='raw-read-failed';content=$null}}
}

function Get-OrchestrationEvidenceMetrics {
    [CmdletBinding()] param([Parameter(Mandatory=$true)][string]$StoreDir)
    $m=[ordered]@{records_created=0;reuse_hits=0;reuse_misses=0;misses_by_reason=@{};lock_busy_skips=0;errors=0;records_skipped_invalid=0};try{foreach($line in [IO.File]::ReadAllLines((Join-Path $StoreDir 'reuse-metrics.jsonl'))){try{$r=ConvertFrom-Json $line;switch([string]$r.metric){'records_created'{$m.records_created++};'reuse_hits'{$m.reuse_hits++};'reuse_misses'{$m.reuse_misses++;$why=[string]$r.reason;if(-not $m.misses_by_reason.Contains($why)){$m.misses_by_reason[$why]=0};$m.misses_by_reason[$why]++};'lock_busy_skips'{$m.lock_busy_skips++};'errors'{$m.errors++};'records_skipped_invalid'{$m.records_skipped_invalid++}}}catch{}}}catch{};$m.lock_busy_skips += [int]$script:OrchestrationEvidenceMetricLockSkips;$m.errors += [int]$script:OrchestrationEvidenceMetricWriteErrors;return [pscustomobject]$m
}
